# Numpy exercices pratiques  

#### Q1 : Importer le package numpy

In [86]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration

In [87]:
print(np.__version__) 
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/xavir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/xavir/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/xavir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/xavir/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/xavir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/xavir/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/xavir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/xavir/anaconda3\\Library\\include']
None


#### Q3 : Créer un vecteur nul de taille 10

In [88]:
v = np.zeros(10, dtype=np.int8)
v

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 5ème place (index 4) du vecteur

In [89]:
v = np.zeros(10, dtype=np.int8)
v[4] = 1
v

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50

In [90]:
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [55]:
np.flip(v)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8

In [44]:
m = np.arange(9).reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3

In [91]:
#v1
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
#v2
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random

In [93]:
np.random.random((3,3,3))

array([[[0.40594362, 0.51739179, 0.33444811],
        [0.68592713, 0.3003303 , 0.79109613],
        [0.8098467 , 0.40216138, 0.80326233]],

       [[0.99427736, 0.00772028, 0.99512981],
        [0.66966294, 0.23322821, 0.16806457],
        [0.10905267, 0.14952854, 0.68658317]],

       [[0.52566336, 0.53777225, 0.14455439],
        [0.33666822, 0.92220282, 0.75428031],
        [0.4965807 , 0.70356043, 0.01235915]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [96]:
m = np.random.random((10,10))
m

array([[0.9196157 , 0.04293687, 0.7591536 , 0.26483014, 0.14665674,
        0.56276183, 0.55589387, 0.19345944, 0.39933437, 0.51689612],
       [0.62564513, 0.32523061, 0.75040804, 0.28151601, 0.54935397,
        0.00575787, 0.64630071, 0.55117783, 0.71663079, 0.00101682],
       [0.76259933, 0.2609072 , 0.53715522, 0.48072986, 0.39225668,
        0.77968935, 0.21038508, 0.05991386, 0.88937394, 0.06831607],
       [0.31765801, 0.53163837, 0.14100484, 0.21045178, 0.3485047 ,
        0.02760295, 0.33454899, 0.92347696, 0.48684598, 0.52447991],
       [0.23234356, 0.15953449, 0.66295001, 0.91334827, 0.33350326,
        0.18132718, 0.46898405, 0.98779687, 0.68397563, 0.84038829],
       [0.6846144 , 0.42741848, 0.96559885, 0.56542318, 0.63214644,
        0.97965343, 0.93342179, 0.21846117, 0.19101245, 0.96827173],
       [0.46407855, 0.50599685, 0.17837489, 0.58263091, 0.69121432,
        0.46533067, 0.36298431, 0.85938416, 0.23779659, 0.25647189],
       [0.76930237, 0.12475364, 0.7838609

In [97]:
print('min', m.min())
print('max', m.max())

min 0.001016817081728405
max 0.987796870230188


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale

In [61]:
#v1
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [62]:
#v2
np.diagflat([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments

In [63]:
l = np.random.random(5)
l

array([0.8388552 , 0.02641659, 0.96452979, 0.60739303, 0.70515669])

In [65]:
l.sum()

3.1423513130563374

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [101]:
#v1
np.average(l)

5.0

In [102]:
#v2
np.mean(l)

5.0

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
l = [x for x in range(11)]

In [105]:
l = [x for x in range(11)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
#v1
np.shape(l)

In [104]:
#v2
np.size(l, axis=0)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS

In [106]:
t = np.linspace(0,1,11,endpoint = False) [1:]
t

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [115]:
tA = [1, 2, 3, 4, 5]
tB = np.flip(tA)
tB

array([5, 4, 3, 2, 1])

In [116]:
np.array_equal(tA, tB)

False

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [122]:
t = np.arange(10, dtype=np.float32)
t

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [123]:
t = t.astype(np.int32, copy=False)
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q18 : Normaliser une matrice random 5x5
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type

In [141]:
m = np.random.random((5,5))
m

array([[0.31896027, 0.2752089 , 0.5474482 , 0.36539594, 0.38746111],
       [0.39775826, 0.70974457, 0.23535954, 0.87619674, 0.33316219],
       [0.57251326, 0.93031568, 0.8848827 , 0.33876959, 0.68858775],
       [0.56104686, 0.24225687, 0.45430375, 0.95930887, 0.3071812 ],
       [0.70699448, 0.32377661, 0.89175791, 0.32973352, 0.46296403]])

In [142]:
m.mean() #moyenne

0.5240435510821607

In [143]:
m.std() #ecart-type

0.23443390769783973

#### Q19 : Créer une matrice random M 2x2 et donner sa transposer
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes.

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)