# Numpy exercices pratiques  

#### Q1 : Importer le package numpy

In [1]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration

In [2]:
print(np.__version__) 
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/xavir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/xavir/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/xavir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/xavir/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/xavir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/xavir/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/xavir/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/xavir/anaconda3\\Library\\include']
None


#### Q3 : Créer un vecteur nul de taille 10

In [3]:
v = np.zeros(10, dtype=np.int8)
v

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 5ème place (index 4) du vecteur

In [4]:
v = np.zeros(10, dtype=np.int8)
v[4] = 1
v

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50

In [5]:
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [6]:
np.flip(v)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8

In [7]:
m = np.arange(9).reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3

In [8]:
#v1
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#v2
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random

In [10]:
np.random.random((3,3,3))

array([[[0.18129353, 0.90810843, 0.71083707],
        [0.43956734, 0.44291875, 0.6032311 ],
        [0.23522901, 0.78048394, 0.30451029]],

       [[0.27039706, 0.49793221, 0.42003972],
        [0.44310946, 0.99307619, 0.18798056],
        [0.1390035 , 0.53997272, 0.07975891]],

       [[0.31014441, 0.89581323, 0.18252082],
        [0.05545343, 0.71646193, 0.60928292],
        [0.87958359, 0.90757832, 0.03803104]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [11]:
m = np.random.random((10,10))
m

array([[0.57838039, 0.88132313, 0.41874997, 0.95776883, 0.73279588,
        0.54873078, 0.82463354, 0.50644619, 0.43278223, 0.59144841],
       [0.32386111, 0.0921859 , 0.99103495, 0.79512472, 0.90920338,
        0.05835895, 0.49603686, 0.957571  , 0.03775452, 0.81275976],
       [0.1874618 , 0.68220734, 0.54870635, 0.78500453, 0.91703738,
        0.64769408, 0.24496953, 0.50550718, 0.14588153, 0.12668951],
       [0.0912852 , 0.30368942, 0.76416381, 0.80902371, 0.62651007,
        0.46317737, 0.40463583, 0.64540834, 0.06227768, 0.79565752],
       [0.42826434, 0.28395461, 0.71439306, 0.20261591, 0.78590442,
        0.58022115, 0.76742042, 0.62903252, 0.16754452, 0.60084144],
       [0.51767785, 0.0057363 , 0.21245653, 0.82860834, 0.46993758,
        0.99319898, 0.99604309, 0.7821575 , 0.84532335, 0.32303295],
       [0.93598634, 0.53571273, 0.05419658, 0.1264573 , 0.26882551,
        0.52351535, 0.89824428, 0.18466856, 0.66965862, 0.88345614],
       [0.10455032, 0.72453198, 0.3696152

In [12]:
print('min', m.min())
print('max', m.max())

min 0.005736304172832329
max 0.9993167740094624


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale

In [13]:
#v1
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [14]:
#v2
np.diagflat([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments

In [15]:
l = np.random.random(5)
l

array([0.65939632, 0.12860421, 0.20970432, 0.73812724, 0.40750948])

In [16]:
l.sum()

2.1433415769857187

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [17]:
#v1
np.average(l)

0.42866831539714373

In [18]:
#v2
np.mean(l)

0.42866831539714373

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
l = [x for x in range(11)]

In [19]:
l = [x for x in range(11)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [20]:
#v1
np.shape(l)

(11,)

In [21]:
#v2
np.size(l, axis=0)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS

In [22]:
t = np.linspace(0,1,11,endpoint = False) [1:]
t

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [23]:
tA = [1, 2, 3, 4, 5]
tB = np.flip(tA)
tB

array([5, 4, 3, 2, 1])

In [24]:
np.array_equal(tA, tB)

False

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [25]:
t = np.arange(10, dtype=np.float32)
t

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [26]:
t = t.astype(np.int32, copy=False)
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q18 : Normaliser une matrice random 5x5
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type

In [27]:
m = np.random.random((5,5))
m

array([[0.55203436, 0.28279112, 0.46608562, 0.43114342, 0.09089023],
       [0.34851924, 0.96732385, 0.36220943, 0.16706356, 0.18760579],
       [0.30624856, 0.77053203, 0.86298914, 0.09925093, 0.91925345],
       [0.59451518, 0.69755808, 0.84360027, 0.01617255, 0.08726851],
       [0.02622873, 0.3094327 , 0.33287149, 0.18126179, 0.4575883 ]])

In [28]:
m.mean() #moyenne

0.4144175331922353

In [29]:
m.std() #ecart-type

0.2863719797093011

#### Q19 : Créer une matrice random M 2x2 et donner sa transposer
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes.

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)